name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby with .ruby-version file
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle config set without 'development'
        bundle install --jobs 4 --retry 3

    - name: Test with Rake
      uses: paambaati/codeclimate-action@v4.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: bundle exec rake
